version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protocolcopilot-api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/protocolcopilot
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  db:
    image: ankane/pgvector:latest  # includes pgvector preinstalled
    container_name: protocolcopilot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: protocolcopilot
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
