version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protocolcopilot-api
    depends_on:
      - db
      - minio
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/protocolcopilot
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=protocols
      - MINIO_SECURE=false
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  db:
    image: ankane/pgvector:latest  # includes pgvector preinstalled
    container_name: protocolcopilot-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: protocolcopilot
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: protocolcopilot-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"   # S3 API endpoint
      - "9001:9001"   # web console
    volumes:
      - minio_data:/data
    restart: always

volumes:
  pgdata:
  minio_data:
